config/routes.rb
Rails.application.routes.draw do
  root "customers#index"

  resources :customers do
    collection do
      get "missing_email"
    end

    collection do
      get "alphabetized"
    end
  end

  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_one_attached :image

  validates :full_name, presence: true
  validates :phone_number, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(full_name: :asc)
  end

  def missing_email
    @customers = Customer.where(email_address: "")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="card">
  <h2><%= customer.full_name %></h2>
  <p>
    <%= image_tag url_for(customer.image) %><br>
    <span class="emph">Phone:</span> <%= customer.phone_number %><br>
    <span class="emph">Email:</span> <%= customer.email_address %><br>
    Notes: <%= customer.notes %>
  </p>
</div>

app/views/customers/alphabetized.html.erb
<h1>All customers in alphabetic order</h1>
<%= link_to "Home", root_path %>
<%= link_to "Missing email", missing_email_customers_path %>

<div class="container">
  <% @customers.each do |customer| %>
    <%= render "customer", customer: customer %>
  <% end %>
</div>

app/views/customers/index.html.erb
<h1>All customers</h1>
<%= link_to "Alphabetized", alphabetized_customers_path %>
<%= link_to "Missing email", missing_email_customers_path %>

<div class="container">
  <% @customers.each do |customer| %>
    <%= render "customer", customer: customer %>
  <% end %>
</div>

app/views/customers/missing_email.html.erb
<h1>All customers missing email</h1>
<%= link_to "Home", root_path %>
<%= link_to "Alphabetized", alphabetized_customers_path %>

<div class="container">
  <% @customers.each do |customer| %>
    <%= render "customer", customer: customer %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>